export const ui = {
  section: 'glass-panel space-y-6 rounded-2xl border border-blue-100/80 p-6 shadow-[0_14px_36px_-20px_rgba(15,23,42,0.45)]',
  sectionTitle: 'text-2xl font-semibold tracking-tight text-slate-900',
  sectionSubtitle: 'text-lg font-semibold text-slate-800',
  headerRow: 'flex flex-col gap-3 md:flex-row md:items-center md:justify-between',
  card: 'rounded-xl border border-blue-100/80 bg-white/95 p-4 shadow-[0_8px_24px_-16px_rgba(15,23,42,0.5)]',
  gridCards: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  formGroup: 'space-y-1.5',
  label: 'block text-sm font-medium text-slate-700',
  input: 'w-full rounded-lg border border-blue-100 px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200/70',
  select: 'w-full rounded-lg border border-blue-100 px-3 py-2 text-sm text-slate-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200/70',
  textarea: 'w-full rounded-lg border border-blue-100 px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200/70',
  btn: 'btn-lift inline-flex items-center gap-2 rounded-lg border border-blue-200 px-3 py-2 text-sm font-medium text-blue-900 transition-colors',
  btnPrimary: 'btn-lift inline-flex items-center gap-2 rounded-lg border border-blue-900 px-3 py-2 text-sm font-medium text-white transition-colors',
  btnSecondary: 'btn-lift inline-flex items-center gap-2 rounded-lg border border-blue-200 px-3 py-2 text-sm font-medium text-blue-900 transition-colors',
  btnDanger: 'btn-lift inline-flex items-center gap-2 rounded-lg border border-red-200 px-3 py-2 text-sm font-medium text-red-700 transition-colors',
  tableWrap: 'overflow-x-auto rounded-xl border border-blue-100/80 bg-white/95',
  table: 'min-w-full border-collapse text-sm bg-white',
  th: 'border-b border-blue-100/80 bg-blue-50 px-3 py-2 text-left text-xs font-semibold uppercase tracking-wide text-blue-900',
  td: 'border-b border-blue-50 px-3 py-2 text-slate-700',
  muted: 'text-sm text-slate-500',
}
