export const ui = {
  section: 'glass-panel space-y-6 rounded-2xl border border-slate-300/80 p-6 shadow-[0_14px_36px_-20px_rgba(15,23,42,0.45)]',
  sectionTitle: 'text-2xl font-semibold tracking-tight text-slate-950',
  sectionSubtitle: 'text-lg font-semibold text-slate-800',
  headerRow: 'flex flex-col gap-3 md:flex-row md:items-center md:justify-between',
  card: 'rounded-xl border border-slate-300/80 bg-slate-100/88 p-4 shadow-[0_8px_24px_-16px_rgba(15,23,42,0.5)]',
  gridCards: 'grid gap-4 md:grid-cols-2 xl:grid-cols-3',
  formGroup: 'space-y-1.5',
  label: 'block text-sm font-medium text-slate-700',
  input: 'w-full rounded-lg border border-slate-300 bg-white/85 px-3 py-2 text-sm text-slate-900 placeholder:text-slate-500 focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-300/70',
  select: 'w-full rounded-lg border border-slate-300 bg-white/85 px-3 py-2 text-sm text-slate-900 focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-300/70',
  textarea: 'w-full rounded-lg border border-slate-300 bg-white/85 px-3 py-2 text-sm text-slate-900 placeholder:text-slate-500 focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-300/70',
  btn: 'btn-lift inline-flex items-center gap-2 rounded-lg border border-slate-400 bg-slate-200/85 px-3 py-2 text-sm font-medium text-slate-900 transition-colors hover:bg-slate-300',
  btnPrimary: 'btn-lift inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-700 px-3 py-2 text-sm font-medium text-white transition-colors hover:bg-slate-600',
  btnSecondary: 'btn-lift inline-flex items-center gap-2 rounded-lg border border-slate-400 bg-slate-200/85 px-3 py-2 text-sm font-medium text-slate-900 transition-colors hover:bg-slate-300',
  btnDanger: 'btn-lift inline-flex items-center gap-2 rounded-lg border border-red-300 bg-red-100/85 px-3 py-2 text-sm font-medium text-red-800 transition-colors hover:bg-red-200',
  tableWrap: 'overflow-x-auto rounded-xl border border-slate-300/80 bg-slate-100/88',
  table: 'min-w-full border-collapse text-sm bg-slate-100/88',
  th: 'border-b border-slate-300/80 bg-slate-200 px-3 py-2 text-left text-xs font-semibold uppercase tracking-wide text-slate-900',
  td: 'border-b border-slate-200 px-3 py-2 text-slate-800',
  muted: 'text-sm text-slate-500',
}
